# Build and validation pipeline
trigger:
- master

variables:
  tags: production, multiphased

jobs:
- job: test_on_ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
      python -m pip install pylint
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      python -m unittest
    displayName: 'Running unit tests [test]'
  - script: |
      pylint genbit
    displayName: 'Running pylint [security-analysis]'
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

- job: test_on_windows
  pool:
    vmImage: windows-latest
  steps:
  - script: |
      python -m pip install --upgrade pip
      python -m pip install pylint
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      python -m unittest
    displayName: 'Running unit tests [test]'
  - script: |
      pylint genbit
    displayName: 'Running pylint [security-analysis]'
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'